bump react-dom to match to new react version, fixes Error: Mismatchin… (#713)
…g "react" dependency versions found: react-dom@19.2.5 (Please change
this to 19.2.6)

## Context
We recently upgraded react with dependabot, need to match versions with
react-dom.
```
Error: Mismatching "react" dependency versions found: react-dom@19.2.5 (Please change this to 19.2.6). All "react" packages must have the same version. This is an error with your set-up, not a
 bug in Payload. Please go to your package.json and ensure all "react" packages have the same version.
```